---
title: "Rubin translation part 2"
output: html_document
---

##BACK TO HARVARD: PROPENSITY SCORE, MULTIPLE IMPUTATION AND MORE##

##回到哈佛：倾向得分，多重插补法及其他##

Fabri: After those productive years at ETS, you spent some time at the EPA (US Environmental Protection Agency). Why did you decide to move, given that you were apparently doing very well at the ETS?

Fabri：您在ETS研究了很多成果之后，就前往EPA（美国环境保护组织）待了一段时间。那么既然您在ETS做的十分出色，为什么突然决定到EPA去？

Don: It started partly from my joking answer to the question, “How long have you been at ETS?” I answered, “Too long.” The problems that I had dealt with at ETS started to appear repetitive, and I felt that I had made important contributions to them including EM and multiple imputation ideas, which were being used to address some serious issues, like test equating, and formulating the right ways to collect data. So I wanted to try something else. At the time, David Rosenbaum was the head of the Ofﬁce of Radiation Programs at the EPA. He had the grand idea of putting together a team of applied mathematicians and statisticians. Somehow he found my name and invited me to D.C. to ﬁnd out whether I wanted to lead such a group. Basically, I had the freedom to hire several people of my choice, and I had a good government salary (at the level of “Senior Executive Service”). So I said, “Let’s see whom I can get.” I was able to convince both Rod Little (who was in England at that time) and Paul Rosenbaum (whom I advised while I was still at ETS), as well as Susan Hinkins, who wrote a thesis on missing data at Montana State University, and two others. That was shortly before the presidential election. Then the Democrats lost and Reagan was to come in, and everything seemed to be falling apart. All of a sudden, many of the people above my level at the EPA (most of whom were presidential appointments), had to prepare to turn in their resignations, and had to be concerned about their next positions.

Don：我之前对于问题“你在ETS工作了多长时间”的开玩笑的回答解释了我的部分想法。我当时回答说“很长的时间”。当时我在ETS处理的问题开始变得重复；而且我觉得我已经帮他们在EM和多重插补法方面做出了很重要的帮助，EM和多重插补法已经可以用来处理一些例如测验等值化，公式化收集数据等重要的问题，所以我想尝试一些其他的东西。当时David Rosenbaum是EPA中放射性项目研究办公室的主任。他有一个想法，想召集一些应用数学家和统计学家组建一支队伍。不知怎么的他找到了我，想看看我是否愿意领导这样一支队伍，并邀请我去D.C.。我当时基本上可以自主选择聘用一些人，而且政府给我拨发了不菲的薪水（待遇同高级管理人员）。所以我说，“我先看看我能找到谁。”我可以叫来Rod Little（他当时在英国）、Paul  Rosenbaum（我在ETS时曾给他提供过建议）和Susan Hinkins（他在蒙大拿州立大学写了一篇有关缺失数据的论文） 以及另外两个人。那会很快就要进行总统选举了。之后民主党下台，共和党掌权，似乎所有的事情就都乱套了。突然很多在EPA比我的职位高的人（他们中大部分人都是总统任命的）开始准备递交他们的辞职信，也在担忧他们接下来会担任什么职务。

Fabri：So the EPA project ended before it even got started.

Fabri：所以EPA的项目还没开始就结束了。

Don: It didn’t start at all in some sense. I formally signed on at the beginning of December, and after one pay period, I turned in my resignation. But I felt responsible to ﬁnd jobs for all these people I brought there. Eventually, Susan Hinkins got connected with Fritz Scheuren at the IRS; Paul Rosenbaum got a position at the University of Wisconsin at Madison; Rod got a job related to the Census. One nice thing about that short period of time is that, through the projects I was in charge of, I made several good connections, such as to Herman Chernoff and George Box. George and I really hit it off, primarily because of his insistence on statistics having connections to real problems, but also because of his wonderful sense of humor, which was witty and ribald, and his love of good spirits. In any case, the EPA position led to an invitation to visit Box at the Math Research Center at the University of Wisconsin, which I gladly accepted. That gave me the chance to ﬁnish writing the propensity score papers with Paul (Rosenbaum and Rubin, 1983a, 1983b, 1984a).

Don：在某种意义上这个项目就是没开始。我在十二月初正式签约，不过只在一个支付期之后，我就递交了自己的辞职信，但我觉得我有义务为我带来的这些人提供工作。最终，Susan Hinkins和IRS的Fritz Scheuren取得了联系；Paul Rosenbaum在威斯康辛大学麦迪逊分校得到了一个职位；Rod也得到了一份有关普查的工作。在这么短的工作时间内，有一件特别棒的事情是，我通过我管理的这个项目，和Herman Chernoff、George Box等人取得了很好的联系。George和我真的很搭，主要是因为他坚持认为统计应该和实际问题相联系，但也有一部分原因是由于他那粗犷而又很诙谐的幽默感，以及他的积极向上。在任何情况下，我都很同意将威斯康辛大学数学研究中心中EPA的位置留给Box。那也给了我一个机会来和Paul一起完成倾向评分（Rosenbaum and Rubin, 1983a, 1983b, 1984a）的论文。

Fan: Since you mentioned propensity score, arguably the most popular causal inference technique in a wide range of applied disciplines, can you give some insights on the “natural history” of propensity score?

Fan：既然你提到了倾向得分，这项可以说是在现在广泛的应用学科中最流行的因果推理技术，那么您能够把倾向评分的发展历程分享给大家吗？

Don: I ﬁrst met Paul in 1978, when I came to Har-vard on a Guggenheim fellowship; he was a ﬁrst-year Ph.D. student, extremely bright and devoted. Back in my Princeton days I did some consulting for a psychologist at Rutgers, June Reinisch, who later became the ﬁrst director of the Kinsey Institute after Kinsey. She was very interested in studying the nature-nurture controversy——what makes men and women so different? She and her husband, who was also a psychologist, were doing experiments on rats and pigs. They injected hormones into the uteri of pregnant animals, and thereby exposed the fetuses to different prebirth environments; this kind of randomized experiment is obviously unethical to do with humans. One of the problems Paul and I were working on for this project, also as part of Paul’s thesis, was matching—matching background characteristics of exposed and unexposed. The covariates included a lot of continuous and discrete variables, some of which were rare events like certain serious diseases prior to, or during, early pregnancy. Soon it became clear that standard matching approaches, like Mahalanobis matching, do not work well in such high dimensional settings. You have to ﬁnd some type of summaries of these variables and balance the summaries in the treatment and control groups, not individual to individual. Then we realized if you have an assignment mechanism, you can match on the individual assignment probabilities, which is essentially the Horvitz–Thompson idea, to eliminate all systematic bias. I don’t remember the exact details, but I think we ﬁrst got the propensity score idea when working on a Duke data bank on coronary artery bypass surgery, but reﬁned it for the Reinisch data, which is very similar in principle. Again, the idea of the propensity score is motivated by addressing real problems, but with generality.

Don：我在1978年，为古根海姆奖去往哈佛时，第一次遇见了Paul；他是个一年级博士生，非常聪明且勤奋。在回到普林斯顿的日子里，我为一名罗格斯大学的心理学家，June Reinisch,做了一些咨询，他后来成为了继Kinsey后的第一位Kinsey研究所的主任。她对于天性和教养问题的研究非常有兴趣——什么导致了男人与女人如此不同？她和同为心理学家的丈夫，在老鼠和猪身上做了一些实验。他们将荷尔蒙注射进了怀孕动物的子宫，从而使得暴露给胎儿的产前环境不同。这种随机性的试验显然在人类身上做是不道德的。我和Paul为这个项目工作时出现了一个问题，是曝光和未曝光的匹配背景特征的问题，同样这也是Paul论文中的一部分内容。这项数据的协方差包括很多离散变量和连续变量，这些变量中有一些是很少见的情况，比如说在早期妊娠期间或者之前出现的各种严重的疾病。但不久我们就发现标准匹配方法，比如说马氏匹配，很明显并不适用在高维的设定中。你需要找到某种变量的分类形式并且在治疗组和控制组中平衡这些集合，（变量在其中）并不是一个对应一个那样。然后我们意识到如果可以有一个分配机制，你就可以对个人的分配概率进行匹配来消除所有的系统误差，本质上是Horvitz–Thompson估计的思想。我记不太清具体的了，但我记得我们在利用杜克数据银行有关冠状动脉搭桥手术的数据时，第一次有了倾向得分的想法。这些数据后来改名为了Reinisch数据，但大致上还是类似的。所以由于实际问题，我们再次有了研究具有普遍性的倾向得分的想法。

Fan: Multiple Imputation (MI) is another very inﬂuential contribution of yours. Your book “Multiple Im-putation for Nonresponse in Sample Surveys” (Rubin, 1987a) has commonly been cited as the origin of MI. But my understanding is that you ﬁrst developed the idea and coined the term much earlier.

Fan：多重插补法（MI）是您另一个有极高影响力的贡献的地方。你的书“Multiple Im-putation for Nonresponse in Sample Surveys”(Rubin, 1987a)通常被认为是MI的起源。但我觉得您第一次提出这个想法并且创造了这个术语要早得多。

Don: Correct, I ﬁrst wrote about MI in an ASA proceedings paper in 1978 (Rubin, 1972, 1978b). That’s where “the 18+ years” comes from when I wrote “Multiple Imputation After 18+ Years” (Rubin, 1996).

Don:是的，我第一次写有关MI的文章是在1978年在一份ASA的记录文件中（Rubin, 1972, 1978b).“Multiple Imputation After 18+ Years” (Rubin, 1996)中“the 18+ years”这个词就是来自于那篇文章。

Fabri: MI has been developed in the context of missing data, but it applicability seems to be far beyond missing data.

Fabri：MI过去在缺失数据的背景下不断发展，但是它的适用性似乎远远超过缺失数据这部分。

Don: Yes, MI has been applied and will be, I think, all over the place. The reason I titled the book that way, “Multiple Imputation for Nonresponse in Sample Surveys,” is that it was obvious to me that in the settings where you need to create public-use data sets, you had to have a separation between the person who ﬁxed up the missing data problem and the many people who might do analyses of the data. So there was an obvious need to do something like this, because users could not possibly have the collection of tools and resources to do the imputation, for example, using conﬁdential information. My Ph.D. students, Trivellore Raghunathan(Raghu) and Jerry Reiter, have made wonderful contributions to conﬁdentiality using MI. Of course, other great Ph.D. students of mine Nat Schenker, Kim Hung Lee, Xiao-Li Meng, Joe Schafer, as well as many others, have also made major contributions to MI. The development of MI really reﬂects the collective efforts from these people and others like Rod Little and his colleagues and students.

Don:是的，我认为MI现在已经并且将会应用于各个领域。我之所以把书名起为“Multiple Imputation for Nonresponse in Sample Surveys”，是因为很显然在你需要创造公共的数据集时，你需要将修复缺失数据问题的人和作分析的人们进行分离。所以我们很有必要做出一些类似（多重插补法）的东西，因为用户可能没有工具和资源进行收集来插补，比如使用一些机密信息时。我的博士生，Trivellore Raghunathan(Raghu)和Jerry Reiter对于利用MI处理机密信息做出了巨大的贡献。当然，我其他的很棒的博士生Nat Schenker, Kim Hung Lee, Xiao-Li Meng, Joe Schafer，以及其他的很多人，也对MI做出了很大的贡献。MI的发展的确是来自于这些人以及其他人如 Rod Little和他的同事学生们的集体努力。

Fabri: Rod Little once half-jokingly said, “Want to be highly cited? Coauthor a book with Rubin!” And indeed he wrote the book “Statistical Analysis with Miss-ing Data” with you (Little and Rubin, 1987, 2002), which is now regarded as the classic textbook on missing data. There have been a lot of new advances and changes in missing data since then. Will we see a new edition of the book that incorporates these developments sometime soon?

Fabri：Rod Little曾经有一次半开玩笑的说：“（你的作品）想要被高度引用吗？和Rubin合著一本书吧！”而且他的确和您合著了“Statistical Analysis with Miss-ing Data” with you (Little and Rubin, 1987, 2002)，这本书现在被认为是缺失数据的经典教材。但从那时起缺失数据方面有了很大的提高和改变。我们之后会不会看到您这本书在整合了这些发展之后的新版本？

Don: Oh yes, we are working on that now. The main changes from 1987 to 2002 reﬂect the greater acceptability of Bayesian methods and MCMC type computations. Rod is a fabulous coauthor, a much more ﬂuid writer than I am. I believe this third edition will have even more major changes than the 2002 one did from the 1987 one, but again many driven by computational advances.

Don：嗯是的，我们现在正在做。从1987到2002年的变化主要体现在贝叶斯方法和MCMC型计算更大的可接受性。Rod是位难以置信的合著者，一名比我厉害得多的作家。我相信第三版的主要变化要多于从1987年那版到2002年那版的变化，但这些改变同样也来自于计算的进步。

##ON BAYESIAN##

##关于贝叶斯##

Fan: In the 1978 Annals paper (Rubin, 1978a), you gave, for the ﬁrst time, a rigorous formulation of Bayesian inference for causal effects. But the Bayesian approach to causal inference did not have much following until very recently, and the ﬁeld of causal inference is still largely frequentist. How do you view the role of Bayesian approach in causal inference?

Fan：在1978年的年报中（Rubin，1978a），您第一次给出了因果效应的贝叶斯推理的严格表述。但是针对因果推断的贝叶斯方法直到最近才有一些后续，而且因果推断领域依然注意是频率统计方面。您怎么看待因果推断的贝叶斯方法？

Don: I believe being Bayesian is the right way to approach things, because the basic frequentist approach, such as the Fisherian tests and Neyman’s unbiased estimates and conﬁdence intervals, usually does not work in complicated problems with many nuisance un-knowns. So you have to go Bayesian to create procedures. You can go partially Bayesian using things like posterior predictive checks, where you put down a null that you may discover evidence against, or direct likelihood approaches as in Frumento et al. (2012); if the data are consistent with a null that is interesting, you live with it. But Neyman-style frequentist evaluations of Bayesian procedures are still relevant.

Don：我相信贝叶斯是正确的逼近事情的方法，因为基本的频率统计方法，比如说Fisherian测试以及Neyman的无偏估计和置信区间经常并不适用处理一些麻烦复杂的未知问题。所以你需要用贝叶斯来模拟过程。当你需要带上和数据一致的空值进行处理时，你可以利用贝叶斯的部分内容比如可能记下一个与事实的空的后测检验，或者（在Frumento等人 (2012)中的）似然法。但是传统风格的频率统计的贝叶斯方法仍然是有重大意义的。

Fan: But why is the ﬁeld of causal inference still predominantly frequentist?

Fan：但是为什么因果推断的领域仍然主要是频率统计方面呢？

Don: I think there are several reasons. First, there are many Bayesian statisticians who are far more interested in MCMC algebra and algorithms, and do not get into the science. Second, I regard the method of moments (MOM) frequentist approach as pedagogically easier for motivating and revealing sources of information. Take the simple instrumental variable setting with one-sided noncompliance. Here, it is very easy to look at the simple MOM estimate to see where information comes from. With Bayesian methods, the answer is, in some sense, just there in front of you. But when you ask where the information comes from, you have to start with any value, and iterate using conditional expectations, or draws from the current joint distributions. You have to have far more sophisticated mathematical thinking to understand fully Bayesian ideas. There are these problems with missing data (as in my discussion of Efron, 1994) where there are unique, consistent estimates of some parameters using MOM, but for which the joint MLE is on the boundary. So I think it is often easier, pedagogically, to motivate simple estimators and simple procedures, and not try to be efﬁcient when you convey ideas. In causal inference, that corresponds to talking about unbiased or nearly unbiased estimates of causal estimands, as in Rubin (1977). There are other reasons having to do with the current education of most statisticians.

Don：我认为主要有这几个原因。首先，有很多的贝叶斯统计学家对MCMC代数和算法要感兴趣得多，而且还没有科学的研究。第二，我认为矩量法（MOM）的频率方法都教学中能更简单的找到信息来源。拿简单的有片面违规设置的工具变量举个例子。我们能够通过简单的MOM估计来看出信息来自哪里。利用贝叶斯方法，答案就仿佛直接放在你面前一样。但当你询问信息从哪里来的时，你需要从任何值开始，重复利用条件期望，或者绘制当前的联合分布。你需要复杂的数学思维方式来完全理解贝叶斯的思想。有缺失数据的一些问题（如我在Efron，1994讨论中讨论的）要利用MOM对一些参数进行特别的一致性估计，但其联合极大似然估计是在边界上。所以我觉得在教学方面，当你传播思想时，应该鼓励使用简单的估计和过程，并且不要太追求效率。在因果推断中，那和讨论因果中无偏或者几乎无偏的估计是一致的，就是在Rubin（1977）中所说的那样。此外大多数统计学家在最近的教育中（这样做）还有一些其他的原因。

Fan: After EM, starting from the early 1980s, you were heavily involved in developing methods for Bayesian computing, including the Bayesian bootstrap (Rubin, 1981), the sampling importance-resampling (SIR) algorithm (Rubin, 1987b), and (lesser-acknowledged) “approximate Bayesian computation (ABC)” (Rubin, 1984, Section 3.1).

Fan：在研究出EM之后，从20世纪80年代初开始，您参与研究了贝叶斯计算方法，包括贝叶斯自举（Rubin, 1981），采样重要性重采样（SIR）算法（Rubin，1987b），和（很少人承认的）“近似贝叶斯计算（ABC）”（Rubin, 1984,3.1版）

Don: It was clear then that computers were going to allow Bayes to work far more broadly than earlier. You, as well as others such as Simon Tavare, Christian Robert and Jean-Michel Marin, are giving me credit for ﬁrst proposing ABC. Thanks! Although, frankly, I never thought that would be a useful algorithm except in problems with simple sufﬁcient statistics.

Don：现在很明显电脑能够让贝叶斯应用的范围比之前广很多。你和其他人比如Simon Tavare, Christian Robert and Jean-Michel Marin，对我提出的ABC给予了肯定。谢谢！但坦白来说，我从未想过在简单的充分统计的问题之外，它可以变成如此有用的算法。

Fabri: But you do not seem to have followed up much on these ideas later, even if you have used them. Also you do not label yourself as a Bayesian or a frequentist, even if all these papers made extraordinary contributions to Bayesian inference with fundamental and big ideas.

Fabri：但是您后来虽然使用了这些想法，但似乎并没有根据这些想法接着研究。同样即便所有这些论文都对贝叶斯推理中基本而又庞大的思想做出了非凡的贡献，您也没有把自己定位成贝叶斯统计学家或者一位频率统计学家。

Don: First of all, fundamentally I am hostile to all “religions.” I recently heard a talk by Raghu in Bamberg, Germany, where he said that in his world they have zillions of gods, and I think that is right; you should have zillions of gods, one for this good idea, one for that good idea. And different people can create different gods to whatever extent they want to. I am not a fully-pledged member of the Bayesian camp—I like being friends with them, but I never want to be religiously Bayesian. My attitude is that any complication that creates problems for one form of inference creates problems for all forms of inference, just in different ways. For example, the fact that confounded treatment assignments cause problems for frequentist inference is obvious. Does it generate problems for the Bayesian?Yeah, that point was made in the 1978 Annals paper: Randomization matters to a Bayesian, although not in the same way as to a frequentist, that is, not as the basis for inference, but it affects the likelihood function.

Don：首先，我基本上对所有的“信仰”都持反对意见。我最近听了一篇演讲，演讲人是德国班贝格的Raghu，他提到在他的世界中有无数个神，我觉得他是对的；首先需要有无数个神，这个神提供了这个好主意，那个神提供了那个好主意，而且不同的人可以创造不同的神来做到他们想要的程度。我不是完全同意贝叶斯学派的一员——我喜欢成为他们的朋友，但我不会变成完全信仰贝叶斯的人。我的态度是任何有可能为某一种推断形式造成麻烦的复杂情况同样也可以对所有的推断形式造成麻烦，只不过是不同的方式。比如，讨厌的分配疗法显然会使频率论推断出现问题。那么贝叶斯会出现问题吗？是的，这个问题在1978年的年报汇总有所提及：贝叶斯中的随机问题。尽管不是像影响到了基本推断那样导致频率统计学派不出现问题，但它也影响到了近似的作用。

There is something I am currently working on with a Ph.D. student, Viviana Garcia, that builds on a paper I wrote with Paul Rosenbaum in 1984 (Rosenbaum and Rubin, 1984b), which is the only Bayesian paper that Paul has ever written, at least with me. In that paper, we did some simulations to show there is an effect on Bayesian inference of the stopping rule. We show that if you have a stopping rule and use the “wrong” prior to do the analysis, like a uniform improper prior, but the data are coming from a “correct” prior, and you look at the answer you get from the right prior and from the “wrong” prior, they are different. The portion of the right posterior that you cover using the “wrong” posterior is incorrect. This extends to all situations and it is related to all of these ignorability theorems, and it means that you need to have the right model with respect to the right measure. Of course achieving this is impossible in practice and, therefore, leads to the need for frequentist (Neymanian) evaluations of the operating characteristics of Bayesian procedures when using incorrect models (Rubin, 1984). Bayes works, in principle, there is no doubt, but it can be so hard! It can work, in practice, but you must have some other principles ﬂoating around somewhere to evaluate the consequences—how wrong your conclusions can be. So you must have something to fall back on, and I think that is where these frequentist evaluations are extremely useful, not the unconditional Neyman–Pearson frequentist evaluations for all point mass priors (which were critical as mathematical demonstrations that we cannot achieve the ideal goal in any generality), but evaluations for the class of problems that you are dealing with in your situation.

我最近正在和我的博士生Viviana Garcia基于我和Paul Rosenbaum在1984年写的文章(Rosenbaum and Rubin, 1984b)继续进行研究，那可能是Paul唯一的贝叶斯文章，至少是和我一起写的唯一的。在那篇文章中，我们做了一些模拟来展示对终止规则的贝叶斯推断有一些影响。我们发现如果你有终止规则并优先使用“错误”来进行分析，就像一致先验那样数据是从“正确”的那面得来的，那么你会发现你从正确那面和错误那面得到的答案是不一样的。你用“错误”的那部分来覆盖正确的部分是不对的。这可以延伸到所有的情况，而且也与所有这些理论有关。这也意味着你需要有针对正确措施的正确模型。当然，这是在实践中不可能实现的，因此，当我们在贝叶斯方法中使用模型不当时，也导致了对频率（neymanian）估计的操作特性的需要（Rubin，1984）。毫无疑问贝叶斯的方法在原理上行得通，但是它的难度非常大！它在实践中可以使用，但是你需要一些其他的原则作为辅助来估计你的结论有多大的偏差。所以你必须有所依靠，我认为这就是频率学的估计方法非常有用的地方，不是无条件的Neyman–Pearson概率估计的先验知识（这是关键的我们无法实现的数学证明），而是在这种情况下估计你所要处理的问题的分类。 

Fan: The 1984 Annals paper “Bayesianly Justiﬁable and Relevant Frequency Calculations for the Ap-plied Statistician” (Rubin, 1984) is one of my all-time favorite papers. This paper, as the earlier paper by George Box (Box, 1980), deals with the “calibrated Bayes” paradigm with generality, which can be viewed as a compromising or midground between the Bayesian and frequentist paradigms. It has a profound inﬂuence on many of us. In particular, Rod Little has strongly advocated “calibrated Bayes” as the 21st cen-tury roadmap of statistics in several of his prominent talks, including the 2005 ASA President’s Invited Address and the 2012 Fisher Lecture. What was the background and reasons for you to write that paper?

Fan：1984年年报上的“Bayesianly Justiﬁable and Relevant Frequency Calculations for the Ap-plied Statistician” (Rubin, 1984)是我一直最喜爱的文章之一。这篇文章，和早期George Box所写的文章(Box, 1980)，都处理了具有一般性的“校准贝叶斯”范式，可以被认为是妥协或者折中的贝叶斯和频率论范式。它对我们许多人都产生了深刻的影响。尤其是是，在包括2005 ASA总统邀请函中和2012年的 Fisher讲座的几个重要会谈中，Rod Little都大力提倡“校准贝叶斯”作为第二十一世纪的路线图。您当时为什么写那篇论文，背景是什么样的？

Don: Interesting question. I was visiting Box at the Mathematics Research Center in 1981–1982 and wrote Rubin (1983) partly during that period—I think it’s a good paper with some good ideas, but without a satisfying big picture. That dissatisfaction led to that 1984 paper—what is the big picture? It took me a very long time to “get it right,” but it all seems very obvious to me now. The idea of posterior predictive checks has been further articulated and advanced in Meng (1994), Gelman, Meng and Stern (1996), and the multiauthored book “Bayesian Data Analysis” (Gelman et al., 1995, 2003, 2014).

Don：非常有趣的问题。我1981至1982年去拜访了在数学研究中心任职的Box，并且在那个时期写了部分的文章（Rubin，1983）——我认为这是一篇有着好的想法的好论文，但并不能让我满意。当时的不满意造就了1984年的那篇论文——什么是我想要的情况？我花了很长时间来构建，但现在对我来说已经很明显了。后测检验的想法在Meng (1994), Gelman, Meng and Stern (1996)的帮助下，在合著的书籍 “Bayesian Data Analysis” (Gelman等人, 1995, 2003, 2014)中有了进一步的明确和提高。

Fabri: Can you talk a little more about the “Bayesian Data Analysis” book, probably one of the most popular Bayesian textbooks?

Fabri：您能不能针对“Bayesian Data Analysis”说得再多一些？这本书可能是最受欢迎的贝叶斯教材之一。

Don: Yup, I think that the Gelman et al. book might be the most popular Bayesian text. It started out as notes by John Carlin for a Bayesian course that he taught when I was Chair sometime in the mid or late 1980s. Andy must have been a Ph.D. student at that time, with tremendous energy for scholarship. John was heading back to Australia, which is his homeland, and somehow the department had some extra teaching money, and we wanted to keep John around for a year—I do not remember the details. But I do remem-ber that the idea of turning the notes for the course into a full text was percolating. Also Hal Stern was an Associate Professor with us at that time, and so the four of us decided to make it happen. We basically divided up chapters and started writing. Even though John’s initial notes were the starting basis, things changed as soon as Andy “took charge.” Quickly, Andy and Hal were the most active. Andy, with Hal, were even more dominant in the second edition, where I added some parts, edited others, but clearly this was Andy’s show. The third edition, which just came out in early 2014, was even more extreme, with Andy adding two coauthors (David Dun-son and Aki Vehtari) because he liked their work, and they had been responsive to Andy’s requests. As the old man of the group, I just requested that I be the last author; Andy obviously was the ﬁrst author, and the second and third were as in the ﬁrst edition. In some ways, I feel like I’m an associate editor of a journal that has Andy as the editor! We get along ﬁne, and clearly it’s a successful book.

Don：好，我认为Gelman等人编的这本书可能的确是最受欢迎的贝叶斯教材。它起初是John Carlin在1980年代中期或后期为准备他教的一门贝叶斯课程而做的笔记，当时我还是主任。Andy 当时应该还是一个获得全额奖学金的博士生。我记不太清了，好像是John要回到他的家乡澳大利亚，而且不知怎么的部门有一些额外的教育资金，所以我们想让John再待一年。但我还记得我们慢慢想到为课程准备的笔记转换为一本教材。同样当时Hal Stern是我们那的副教授。所以我们四个决定让想法成为现实。我们大体分了章节，然后开始编写。尽管最初是基于John的笔记来写，但逐渐就变成了Andy在负责。很快，Andy和Hal成为了最活跃的。在第二版中，Andy和Hal更加活跃，我当时加了一些内容，尽管编辑的人增加了，但是主要的还是Andy的功劳。2014年初出的第三版甚至更极端，Andy又加了两名合著者（David Dun-son和Aki Vehtari），因为Andy喜欢他们的著作，而且他们同意了Andy的请求。作为这个团体中的“老人”，我请求把自己当成是最后的作者，Andy显然会是第一作者，然后第二第三作者和第一版的是相同的。在某些方面，我觉得我是一个杂志的副主编，而安迪则是编辑！我们相处的很好，而且显然这是一本很成功的书籍。

Fan: A revolutionary development in statistics since the early 90s was the MCMC methodology. You left your mark in this with Gelman, proposing the Gelman–Rubin statistic for convergence check (Gelman and Rubin, 1992), which seems to be very much connected to some of your previous work.

Fan：自90年代初，统计学界有一场革命性的发展就是MCMC方法。您和Gelman一起留下了自己的一笔，提出了Gelman-Rubin统计收敛检查（Gelman and Rubin, 1992），这个成果似乎和您之前的某些成果有很多的联系。

Don: Correct. We embedded the convergence check problem into the combination of the multiple imputation and multiple chains frameworks, using the idea of the combining rules for MI. The idea of using multiple chains—that comes from physics—and was Andy’s knowledge, not mine. My contribution was to suggest using modiﬁed MI combining rules to help do the assessment of convergence. The idea is powerful because it is so simple. If the starting value does not matter, which is the whole point, then it doesn’t matter, period. The real issue should be how you choose the functions of the estimands that you are assessing, and as always, you want convergence to asymptotic normality to be good for these functions, so that the simple justiﬁcation for the Gelman–Rubin statistic is roughly accurate.

Don：是的。我们利用MI的组合规则的想法，将收敛检查问题嵌入多重插补和多重链框架之中。但利用多重链这个来自于物理学的想法是Andy提出的，不是我。我的贡献只是建议使用改进的MI组合规则来帮助做评估收敛。这个想法非常好，因为它是如此简单。如果整点起始值不影响过程，那么就没关系。真正的问题应该是如何选择你评估的作用，和往常一样，你想要收敛到渐近正态来有利于使用这些作用，所以对Gelman–Rubin 统计进行简单的调整是需要很准确的。

##THE 1990S: COLLABORATING WITH ECONOMISTS##

##1990年代：与经济学家合作##

Fabri: In the 1990s, you started to work with economists. With Joshua Angrist, and particularly with Guido Imbens, you wrote a series of very inﬂuential papers, connecting the potential outcomes framework to causal inference with instrumental variables. Can you tell us how this collaboration started?

Fabri：在1990年代，您开始和经济学家合作。和Joshua Angrist,尤其是和Guido Imbens,您写了一系列很有影响力的论文，将潜在结果框架与与工具变量因果推论联系了起来。您能告诉我们这次合作是怎么开始的吗？

Don: Absolutely. I always liked economics; many economists are great characters! It was in the early 90s when Guido came to my ofﬁce as a junior faculty member in the Harvard Economics Department and basi-cally said, “I think I have something that may interest you.” I had never met him before, and he was asking if the concept of instrumental variables already had a history in statistics. Guido and Josh Angrist had already deﬁned the LATE (local average treatment effect) in an Econometrica paper (Imbens and Angrist, 1994)—although I think CACE (Complier Average Causal Ef-fect) is a much better name because it is more descrip-tive and more precise—local can be local for anything, local for Boston, local for females, etc. Then I asked in return, “Well tell me the setup, I have never heard of it in statistics before” and while he was explaining I started thinking, “Gosh, there is something important here! I have never seen it before,” and then I said, “Let’s meet tomorrow and talk about it more,” because these kinds of assumptions (monotonicity and the “exclusion restriction”) were fascinating to me, and it was clear that there was something there that I had never really thought hard about; it was great. That eventually led to the instrument variables paper (Angrist, Imbens and Rubin, 1996) and the later Bayesian paper (Imbens and Rubin, 1997).

Don：当然可以。我一直都很喜欢经济；许多经济学家都非常好！在90年代早期，Guido作为哈佛经济学系初级教员，来到了我的办公室，说：“我认为我有些东西你会感兴趣。”我之前从未见过他，他还问我工具变量的概念是不是在统计学中已经有一段时间了。Guido和Josh Angrist当时已经在计量经济学论文中定义了LATE(local average treatment effect)(Imbens and Angrist, 1994)，尽管我认为CACE (Complier Average Causal Effect)是一个更好的名字，因为它更多更精确的描述本地的什么，比如当地的Boston，当地的女性等等。然后我反问他：“好，那么请告诉我是什么样的吧，我之前从未在统计中听说过”。当他解释的时候，我开始想：“天啊！这些东西一定很重要，我之前从未见过。”然后我说“我们明天见面详谈吧。”因为这些类型的假设（单调性和“排除限制”）吸引着我，而且很明显是我之前没想过没听过的，这些都很棒。这最终导致了有关工具变量的论文(Angrist, Imbens and Rubin, 1996)和之后的贝叶斯论文 (Imbens and Rubin, 1997)。

A closely related development was a project I was consulting on for AMGEN at about the same time, for a product for the treatment of ALS (amyotrophic lateral sclerosis), or Lou Gehrig’s disease, which is a progressive neuromuscular disease that eventually destroys motor neurons, and death follows. The new product was to be compared to the control treatment where the primary outcome was quality of life (QOL) two years post-randomization, as measured by “forced vital capacity” (FVC), essentially, how big a balloon you can blow up. In fact, many people do not reach the endpoint of two-year post-randomization survival, and so two-year QOL is “truncated” or “censored” by death. People were trying to ﬁt this problem into a “missing data” framework, but I realized right away that it was something different.

当时同一时间还有一个我为AMGEN提供咨询的项目，这个项目和（刚才所说的）研究密切相关。我是为了研究用于治疗ALS（肌萎缩性侧索硬化症），或Lou Gehrig氏病的产品，Lou Gehrig氏病是一种渐进的神经肌肉疾病，会破坏运动神经元，最终死亡。新产品是进行对照处理，主要的结果是检测生活质量（QQL），根据用力肺活量（FVC），即你能够一口气吹起多大的气球，来进行两年后的随机分组。事实上，很多人都到不了两年后随机分组时就死了，所以两年期的生活质量检测是被死亡“截断”了的。人们试图通过缺失数据的框架来修补这个问题，但我马上意识到这是和之前不同的东西。

Fan: Essentially both ideas are special cases of the general idea of Principal Stratiﬁcation, which we can discuss in a moment.

Fan：这两个主意都是有关主分层想法的特殊案例，我们可以讨论一下。

Don: Yes, indeed. These meetings with Guido and this way of thinking were so much more articulated and close to the thinking of European economists in the 30s and 40s, like Tinbergen and Haavelmo, than many subsequent economists who seemed sometimes to be too into their OLS algebra in some sense. There was some correspondence between one of the two—Haavelmo, I think—and Neyman on these hypothetical experiments on supply and demand. European brains were talking to each other, and not simply exchanging technical mathematics!

Don：是的，的确是这样。我和Guido的会面以及这种思维方式都很明确和接近在30年代和40年代欧洲经济学家的思维，比如说Tinbergen和Haavelmo，而不像之后很多在某种意义上太投入于他们的普通最小二乘法的经济学家。他们两中的一个——应该是Haavelmo——和Neyman在这些有关供应和需求的假设试验上有很多的来往联系。欧洲人的确是在相互进行交谈，而不是简单地交流应用数学的内容！

Fabri: I know that many years before you met Guido, with other statisticians, like Tukey, you had discussions about the way economists were treating selection problems, or missing data problems. But you had some adventurous, to say the least, previous experiences with economists dealing with problems that you had worked on, which they had almost neglected completely.

Fabric：我知道在你遇见Guido之前很多年，你和其他的统计学家，比如Tukey，有一些有关经济学家如何处理选择问题以及缺失数据问题的讨论。但是你有些冒险，之前你一直致力于解决经济学家的问题，他们至少可以说是几乎完全忽视。

Don: Yes, James Heckman was tracking my work in the early 1980s when I came to Chicago after ETS. The public exchange came out in the ETS volume edited by Howard Wainer (which is where Glynn, Laird and Rubin, 1986, appears), with comments from Heckman, Tukey, Hartigan and others.

Don：是的，James Heckman在1980年代初期我离开ETS到芝加哥后，就开始继承我的工作。公开的变化是ETS卷由Howard Wainer主编出版（里面有Glynn, Laird and Rubin，1986的文章），以及有来自Heckman，Tukey，Hartigan以及其他人的评论。

Fabri: Economics is a ﬁeld where the idea of causality is crucial; did you ﬁnd interest in economics also for this very reason? The problems they have are usually very interesting.

Fabri：经济学这个领域因果理念非常的关键，您也是因为这个原因对经济学感兴趣的吗？经济中出现的的问题通常都很有意思。

Don: There are often interesting questions from social science students that come up in class. One recent example is how do we answer questions like “What would the Americas be like if they were not settled by Europeans?” I asked the questioner, “Who would they be settled by instead? By the Chinese? By the Africans? What are you talking about? What are we comparing the current American world to?” Another example comes from an undergraduate thesis that I directed, by Alice Xiang, which won both the Hoopes Prize and the economics’ Harris Prize for an outstanding honors thesis. The thesis is on the causal effect of racial afﬁrmative action in law school admissions on some outcomes versus the same proportion of afﬁrmative action admissions but counter-factually based on socioeconomic status. This is not just for cocktail conversation—it was a case recently before the US Supreme Court, Fisher v. University of Texas, which was kicked back to the lower court to reconsider, and additionally the issue was recently affected by a state law in Michigan. There is an amicus brief sent to the US Supreme Court to which Guido (Imbens), former Ph.D. students, Dan Ho, Jim Greiner and I (with others) contributed.

Don：班上社会科学的学生经常会提出一些非常有意思的问题。最近有一个例子是我们应该如何回答类似“如果不是欧洲人定居，那么美国会变成什么样”的问题。我问那个问问题的人：“谁会替代欧洲人定居在美国？中国人？非洲人？你想要说什么？我们拿现在的美国和谁去比较？”另一个例子是由Alice Xiang提出的，他通过本科的毕业论文赢得了胡普斯奖和经济学奖。那篇文章是关于法学院中基于种族活动通过的比例与基于社会经济地位活动通过的比例所进行的比较。这不是简单的一个故事，而是一个事件，最近在美国最高法院中有一个德克萨斯大学的案件，这一案件被驳回了下级法院重新考虑，另外这一案件最近也受到密歇根州法律的影响。Guido（Imbens），以前的博士生，Dan Ho，Jim Greiner和我（和其他人）写了一个法庭简短递送到了美国最高法院。 

Such careful formulation of questions is something critical, and to me is central to the ﬁeld of statistics. It is crucial to formulate clearly your causal question. What is the alternative intervention you are considering, when you talk about the causal effect of afﬁrmative action on graduation rates or barpassage rates? Immediately formulating the problem as an OLS regression is the wrong way to do this,at least to me.

这种需要仔细制定公式的问题是非常关键的，对我来说是统计学的范畴。清楚地阐述你的因果关系是非常重要的。当你讨论到活动通过率和毕业率或者禁止通行率之间的因果关系时，你正在考虑替代的是什么？至少对我来说，立刻将其公式化转为OLS进行解决是错误的。

Fan: You apparently have a long interest in law; besides the aforementioned “afﬁrmative action” thesis, you have done some interesting work in applied statistics in law.

Fan：您看来对于法律一直都很有兴趣；除了上述“通过率行动”的论文，您还做过什么有趣的工作，将统计应用于法律中？

Don: Yes. Paul Rosenbaum was, I think, the ﬁrst of my Harvard students who did something about statistics in law. Either his qualifying paper or a class paper in 1978 was on the effect of the death penalty. Jim Greiner, another great Ph.D. student of mine, who had a law degree before entering Harvard Statistics, wrote his Ph.D. thesis (and subsequently several important papers) on potential outcomes and causal effects of immutable characteristics. He is now a full professor at the Harvard Law School. There were also several previous undergraduate students of mine who were inter-ested in statistics and law, but (sadly) most went to law school. Since 1980, I have been involved in many legal topics.

Don：是的，还有。我认为Paul Rosenbaum是我在哈佛中第一个把统计应用于法律中的学生。无论是他1978年的学年论文还是课堂论文，都是有关死刑的影响。Jim Greiner,我另一个很棒的博士生，在进入哈佛统计系前有一个法学学位，他的博士论文（以及很多重要的论文）都是有关不可变性的潜在结果和因果效应。他现在是哈佛法学院的全职教授。我同样之前有一些本科生对统计学和法学都很感兴趣，但（遗憾的是）大部分都去了法学院。从1980年起，我就参与了很多的法律话题。

##THE NEW MILLENNIUM: PRINCIPAL STRATIFICATION##

##新千年：主分层##

Fabri: The work you did with Guido, as well as the work on censoring due to death, led to your paper on Principal Stratiﬁcation (Frangakis and Rubin, 2002), coauthored with this brilliant student of yours, Con-stantine Frangakis, who happens to be Fan’s advisor.

Fabri：您和Guido所做的工作，以及由于死亡而进行的普查工作，促使您和您极棒的学生，Constantine Frangakis一起发表了有关主分层的论文（Frangakis and Rubin, 2002），他碰巧也是Fan的顾问。

Don: Yes, Constantine is fabulous, but the original title of that paper was very long, same with the title of his thesis. It went on and on, with probably a few Latin,a few Italian, a few French and a few Greek words!Of course I was exasperated, so I convinced him to simplify the paper’s title to “Principal Stratiﬁcation in Causal Inference.” He is brilliant, so good that he has no trouble dealing with all the complexity in his own mind, but therefore he struggles at times pulling out the kernels of all these ideas, making them simple.

Don：是的，Constantine非常好，但是最起初的论文题目非常长，和他的论文题目一样。它不断变长，有一些拉丁字母，一些意大利文，一些法文和一些希腊字母！当然我很恼火，所以我说服了他来简化文章的标题，变成了“Principal Stratiﬁcation in Causal Inference”。他很聪明，所以它对于处理脑中的复杂事情没有问题，但他也尝试着把所有这些想法的精华拿出来，让他们变得简单。

Fan: What do you think is the most remarkable thing about the development of Principal Stratiﬁcation?

Fan：您认为在主分层的发展过程中哪件事情是最值得铭记的？

Don: It is a whole new collection of ways of thinking about what the real information is in causal problems. Once you understand what the real information is, you can start thinking about how you can get the answers to questions that you want to extract from that information; you always have to make assumptions, and it forces you to explicate what these assumptions are, not in terms of OLS, which no social scientist or doctor would really understand—but in terms of scientiﬁc or medical entities. And because you have to make assumptions, be honest and state them clearly. For example, I like your papers (Mealli and Pacini, 2013; Mattei, Li and Mealli, 2013) about multiple post-randomization outcomes, where you discuss that for some outcomes, exclusion restriction or other struc-tural assumptions may be more plausible.

Don：这是一种全新的收集因果问题中真正有用的信息的方式。一旦你理解了什么是真正有用的信息，你可以开始考虑如何从那些信息中提取出问题的答案。你需要作假设，这会迫使你需要说明这些假设是什么，不是通过OLS那种没有社会科学家或者博士能够理解的角度，而是从科学或者医学的角度。而且由于你需要作出假设，所以要坦诚清楚地陈述出来。举个例子，我喜欢你有关多随机化结果的论文（Mealli and Pacini, 2013; Mattei, Li and Mealli, 2013），你在论文中提到了对于一些结果，排除限制或其他结构的假设可能是更合理的。

Fabri: Principal Stratiﬁcation is sometimes compared to other tools for doing so-called mediation analysis—what is your view about inferring on mediation effects?

Fabri：主分层有时会和为了所谓的中介分析的其他工具相比较，您是怎么看待它在中介作用上的影响的？

Don: I think we (Don and Fabri) discussed a paper recently in JRSS-A, and those discussions summarize my–our view on that. Essentially, some of the people writing about mediation seem to misunderstand what a function is. They write down something that has two arguments inside parenthesis, with a comma separating them, and they seem to think that therefore something is well deﬁned!

Don：我觉得咱们（Don和Fabri）是在讨论最近JRSS—A上的一篇文章，而且这些讨论结果总结了我们的观点。从本质上讲，一些些有关中介作用文章的人似乎误解了它的作用是什么。他们写了一些东西，括号里面有两个参数，用逗号分隔，然后他们就觉得这个就已经定义很清楚了。

Fan: Even though causal inference has gained increasing attention in statistics and beyond, there seems to be a lot of misunderstanding, misuse, misinterpretation and mystifying of causal inference. Why? And what needs to be done to change?

Fan：尽管因果推断在统计界受到越来越多的关注，现在似乎仍然有很多的误解，误用，将其神秘化，为什么？我们需要如何改变？

Don: I think it is partly because causal inference is a very different topic from many topics in statis-tics in that it does not demand a lot of technical advanced mathematical knowledge, but does demand a lot of conceptual and basic mathematical sophistication. Principal Stratiﬁcation is one such example. Writing down notation does not take the place of understanding what the notation means and how to prove things mathematically. Also partly because causal inference has become a popular topic, it has been ﬂooded with publications that are often done casually. For some ﬁelds, it is important to bridge the “old” (everything-based-on-OLS) thinking with the newer ideas. That’s a battle Guido and I constantly had to deal with when writing our book (Imbens and Rubin, 2015).

Don：我认为这是因为因果推理是一个在统计学中与其它很不同的话题，而且它也不需要很多技巧性很高等的数学知识，但需要大量的概念和基本数学的较高程度。主分层就是这样的一个例子。记下符号并不能代替理解符号的意思以及知道如何用数学来证明事物。另外还有一部分原因是因果推断已经成为一个热门的话题，它在出版物中已经时不时被提到了。在某些领域，它是联系老方法（基于OLS的一切事物）和新想法的桥梁。那是一场我和Guido在写书（Imbens and Rubin, 2015）时需要打赢的战役。

Fan: You mentioned the book; when will it ﬁnally come out? It has been forthcoming for the last ten years or so.

Fan：您提到了那本书，那本书什么时候能最终发行？它在过去的十年左右就开始准备出版了。

Don: (Laughing) Come on, Fan, that’s not fair! Has it only been ten years? We have promised the publisher (Cambridge University Press) that it will be ready by September 30, 2013. It will be about 500 pages, 25 chapters. It will be followed by another volume, dealing with topics that we could not get to in the volume due to length, such as principal stratiﬁcation beyond IV settings, or because we believe the topics have not been sharply and cleanly formulated yet, such as regression discontinuity designs, or using propensity scores with multiple treatments. Also in this volume, we didn’t discuss so-called case–control studies, which are the meat of much of epidemiology; it is very important to embed these studies into a framework that makes sense, not just teach them as a bag of tricks.

Don：（大笑）嘿，Fan，那不公平！到现在只有十年吗？我们许诺给出版商（剑桥大学出版社）在2013年9月30号它就可以完成。它会有500页，25章。这将是另一卷来面对我们由于长度而无法处理的话题，比如说在四维智商的主分层，或者是一些因为相信这个话题还没有直截了当地用公式表示出来的话题，比如回归不连续的设计，或者将倾向得分和多重处理相结合。同样在这一本中，我们不会考虑所谓的案例——控制研究，那是许多流行病学的菜。将这些研究嵌入到一个有意义的框架中是非常重要的，而不仅仅是只把它们作为一个技巧包。 

##MENTORING, CONSULTING AND EDITORSHIP##

##指导，咨询和编辑##

Fabri: You have advised over 50 Ph.D. students and many BA students as well. This sounds like a job inter-view, but what is your teaching philosophy?

Fabri：您曾经给超过50名博士生以及许多本科生提过建议。这听上去像求职面试，那您的教学理念是什么？

Don: My view is that one should approach teaching very differently depending on the kind of students you have and their goals. Harvard has tremendous under-graduate and graduate students, but their strengths vary and their objectives vary. A long time ago I decided that I don’t have the desire or ability to be an entertainer in class, that is, to entertain to get their attention. If they ﬁnd me entertaining, ﬁne; but it is better if they ﬁnd the topic I am presenting entertaining.

Don：我的观点是，一个人应该以不同的方式对待教学，这取决于你有什么样的学生和他们的目标。哈佛大学毕业生和研究生都很庞大，但他们的优势各不相同，他们的目标也各不相同。很久以前我就发现我没有欲望或能力成为一个在课堂上活跃气氛，得到他们注意的人。如果他们觉得我很有意思，这很好；但我觉得如果他们觉得我正在讲述的话题很有意思，那就更好了。

Fabri: Many of your students went on to become leaders and not only in academia. And you often say that the thing that you are the most proud of is your students. Though it is clearly impossible to talk about them here one by one, can you share some of your fond memories of the students?

Fabri：您的很多学生成为了各行各业的领袖。您经常说您最自豪的就是您的学生。虽然在这里一个接一个地谈论他们显然是不可能的，但您能否分享一些您和学生的美好回忆吗？

Don: Fabri, that is a killer question unless we have another day for this. What I can say is that it has been a great pleasure to supervise so many very talented students. I could start listing my superb Ph.D. students at the University of Chicago and at Harvard. All of my Ph.D. students are talented in many, and sometimes different, dimensions: among them there are two COPSS award winners, one president of the ASA, one president of ENAR, two JSM program chairs, and other such honors, and many of them made substantial contributions to government, academia and industry.

Don：Fabri，这可是个很能打发时光的话题啊，我们可以改天再聊。我能说的是，能教授很多很有天赋的学生的确是一大乐趣。我可以开始列出我在芝加哥大学和哈佛的优秀博士生。我所有的博士生在各行各业都非常出彩：在这其中有两位COPSS奖的获奖者，有一位ASA的主席，有一位ENAR的主席，两位JSM的项目主任以及其他很多。他们很多人都为政府、学术界。工业做出了不可替代的贡献。

Fan: You also have advised a large number of undergraduate students on a wide range of topics. This is quite uncommon because some people ﬁnd mentoring undergraduates more challenging and less rewarding than mentoring graduate students. What is your take on this?

Fan：您还建议了许多本科生广泛研究主题。这是相当罕见的，因为一些人认为本科生导师比研究生导师更有挑战性而更少回报。您对此有什么看法？

Don: I am not completely innocent on this charge. I have no interest in “babysitting” and trying to mo-tivate unmotivated students, either undergraduate or graduate. But Harvard does attract some extremely tal-ented and motivated undergraduates, some of whom I had the pleasure to advise. Five have won Hoopes and other prizes for outstanding undergraduate theses.

Don：对于这种想法我也有一些责任，我对于“保姆”式的教学以及激励那些自身没有动力的人没有兴趣，无论是本科生还是研究生。但是哈佛确实吸引了一些非常有天赋而又努力的本科生，我很想为他们提供建议。他们中有五个由于优秀本科毕业论文而获得了胡普斯奖。

Fabri: Now let’s talk about writing, which both Fan and I, as many others, have some quite memorable ﬁrst-hand experience. You are known as a perfectionist in writing. As you mentioned, you are willing to with-draw accepted papers if you are not a hundred percent satisﬁed with them.

Fabri：现在我们来讨论一些写作，Fan和我，和其他很多人一样，有一些非常难忘的第一手经验。您是一位出色的作家，正如您所提到的那样，只要您对论文不是百分百愿意，就算别人接受了，您也希望撤回自己的论文。

Don: Yes, as you guys know, I am generally a pain in the neck as a coauthor. I have withdrawn three accepted papers, and tried to improve them; all eventually got reaccepted. One of these is the paper with you guys and others on multiple imputation for the CDC Anthrax vaccine trial (Li et al., 2014). You were not too happy about it initially.

Don：是的，正如你们所知道的那样，我通常有点讨厌合著。我当时拿回了三篇已经通过的文章，然后尝试再修改它们；最终所有的文章都再次通过了。其中之一就是与你和其他人对CDC的炭疽疫苗试验的多重插补法（李等人，2014）的论文。你最初不是很高兴。

Fabri: (Laughing) Yeah, we tried to revolt without success. A different question: How do you approach rejections? Do you have some advice for young statis-ticians on that?

Fabri：（大笑）是的，我们试图反抗却没有成功。一个很特别的问题：您如何处理拒绝的情况呢？您能不能给年轻的统计学家们提供一些建议？

Don: Over the years I had many papers immediately rejected or rejected with the suggestion that it would not be wise to resubmit. However, in almost all of these cases, this treatment led to markedly improved publications, somewhere. In fact, I think that the drafts that have been repeatedly rejected possibly represent my best contributions. Certainly, the repeated rejections, combined with my trying to address various comments, led to better exposition and sometimes better problem formulation, too. The most important idea is: Do not think that people who are critics are hostile. In the vast majority of cases, editors and reviewers are giving up their time to try to help authors, and, I believe, are often especially generous and helpful to younger or inexperienced authors. Do not read into rejection letters personal attacks, which are extremely rare. So my advice is: Quality trumps quantity, and stick with good ideas even when you have to do polite battle with editors and reviewers—they are not perfect judges, but they are, almost uniformly, on your side. More details of these are given in Rubin (2014b).

Don：多年来我有许多文章被立刻拒绝或者被拒绝伴随着“提交是不明智的”建议。然而，几乎在所有这些情况下，这种对待方式引领着国家不断提高。事实上，我认为那些一再被否决的草稿可能代表了我最佳的贡献。当然，一再拒绝，加上我试图解决的各种评论，可能会产生更好的阐述以及更好的解决办法。最重要的一点是：不要认为批评你的人是有敌意的。在绝大多数情况下，我相信，编辑和审稿人都会放弃自己的时间来帮助作者而且往往会在面对年轻的或经验不足的作者时更不吝啬自己的帮助。别把拒绝理解为个人攻击，这是极为少见的。所以我的建议是：质量胜于数量，坚持自己好的想法，即使你需要不断地和编辑与审稿人进行礼貌的战斗，他们不是完美的评判人，但他们几乎都是站在你这边的。更多的细节可以在Rubin（2014b）中找到。 

Fan: In 1978, you became the Coordinating and Applications Editor of JASA. Is there anything particularly unique about your editorship?

Fan：在1978年，您成为了JASA的协调与应用编辑。在您作为编辑的日子里，有什么独特的事情吗？

Don: As author, I am willing to withdraw accepted papers. As a new editor, at least then, I was also willing to suggest to authors that they withdraw papers ac-cepted by the previous editors! I took some heat for that at the beginning. I read through all the papers that the previous editorial board had accepted and were awaiting copyediting for publication; for the ones that I thought were bad (I remember there were about eight), I wrote, “Dear authors, I think you should consider withdrawing this paper,” with long explanations of why I thought it would be an embarrassment to them if the paper were published. Fabri knows that I can be brutally frank about such suggestions.

Don：作为作者，我愿意撤回那些之前已经接受的文章。作为一名新编辑，至少在那会，我还是愿意建议那些作者撤回那些之前编辑接受了的文章的。我起初还是非常费了很大的心力的。我阅读了所有之前编辑答应登刊并且等待印刷出版的论文；对于那些我认为不好（我记得一共有八篇），我给他们写到：“亲爱的作者，我认为你应该考虑撤回这篇论文”后面附着我为什么举得如果论文出版了对他们来说并不是很好的长长的解释。Fabri知道我当时那些建议有多直白坦诚。

Fan: Did they comply?

Fan：他们同意了吗？

Don: Yes, all but one. This one author fought, and I kept saying, “You have to ﬁx this up.” Eventually, the changes made the paper OK. For the other ones, the authors agreed with my criticisms: Just because the previous editor didn’t get a good reviewer or they over-looked mistakes, does not mean the paper should appear. But I was not very popular, at least at ﬁrst.

Don:是的，只有一个没同意。这个作者不断抗争，但我坚持说：“你需要改一下它。“渐渐地，他做的改变让论文可以通过了。还有另外一个作者，他对我的意见表示赞成：只是因为先前的编辑没有好好翻看文章或者发现问题，并不代表这篇论文就可以在刊物上出现。但我并不是很感冒，至少起初是这样。

Fabri: You have done a wide range of consulting. What is the role that consulting plays in your research?

Fabri：您之前做过广泛的咨询，咨询在您的研究中扮演什么样的角色？

Don: To me consulting is always a stimulating source of problems. As I mentioned before, for example, propensity score technology partly came from the consulting work we did for June Reinisch.

Don：对于我来说咨询就是问题解决的一个来源。正如我之前所提到的那样，比如说倾向得分的技术有部分来自于我们为June Reinisch所做的咨询工作。

Fabri: One of the more controversial cases in which you are involved as a consultant is the US tobacco litigation case, in which you represented the tobacco companies as an expert witness. Would you mind sharing some of your thoughts on this case?

Fabri：有一个很具争议性的案件是当时您作为顾问参与美国烟草诉讼案，在这其中您代表烟草公司作为一个专家证人。您能给我们分享一下您当时的想法吗？

Don: Happy to. This comes from my family background dealing with lawyers. We have a legal system where certain things are legal, certain things are not. You should generally obey laws even if you don’t like them, or you should try to change them. If a company is making a legal product, and they are advertising it legally under current laws, then accept it or work to change the laws. If they lie, punish them for lying, if that is legal to do. You never see a commercial for sporty cars that show the cars going around corners extremely slowly and safely. How do they advertise cars?They usually show them sweeping around corners, and say “Don’t do this on your own.” Things that are enjoyable typically have uncertainties or risks associated with them. Flying to Europe to visit Fabri has risks!

Don：乐意之至。这是来自于和律师有关的家族背景，我们有一套法律系统告诉我们什么是合法的，什么不是。你应该遵守法律即使你不喜欢它们，或者你应该尝试改变它们。如果一个公司在生产合法的产品，而且他们在现有的法律条款下合法的利用广告，那么我们就应该接受它或者尝试改变法律。如果他们欺骗我们了，惩罚他们是合法的，那么他们就应该因此受到惩罚。你从来没有看到一个跑车的广告上面写着汽车拐弯时平稳安全。他们如何宣传汽车？他们通常会展示汽车开过拐角，并说“请勿模仿”。那些看上去令人愉快的事情通常有不确定性或与他们相关的风险。比如飞往欧洲去拜访Fabri是有风险的！ 

Certainly I do not doubt that no matter how I would intervene to reduce cigarette smoking, lung cancer rates would drop. But what intervention that would reduce smoking would involve reducing illegal conduct of the cigarette industry—that is the essence of the legal question.

当然，我毫不怀疑，无论我如何干预来减少吸烟，肺癌率都将不断下降。但什么样的减少吸烟的干预能够减少卷烟行业的非法行为，是这个法律问题的实质。

When I was ﬁrst contacted by a tobacco lawyer, I was very reluctant to consult for them, and I feared strong pressure to be dishonest, which was absent throughout. The original topic was simply to comment on the ways the plaintiffs’ experts were handling missing data. On examination, their methods seemed to me to be not the best available and, at worst, silly (e.g., when missing “marital status,” call them “married”). As I continued to read these initial reports, I was appalled that hundreds of billions of dollars could be sought on the basis of such analyses. From a broader perspective, the logic underlying most of the analyses also seemed to me entirely confused. For example, alleged misconduct seemed to play no role in nearly all calculations, and phrases such as “caused by” or “attributable to,” were used nearly interchangeably and often apparently without thought. Should nearly a trillion dollars in damages be awarded on the basis of faulty logic and bad statistical analyses because we “know” the defendant is evil and guilty? If the issue were assessing the tobacco industry a trillion dollar ﬁne for lying about its products, I would be amazed but mute. But these reports were using statistical arguments to set the numbers—is it acceptable to use bad statistics to set numbers because we “know” the defendant is guilty? What sort of precedent does that imply? The ethics of this consulting is discussed at some length in Rubin (2002).

Don：当我第一次和烟草行业的律师接触，我对向他们提供咨询是很不情愿的，我害怕不诚实会成为我巨大的压力，但实际上是不存在的。最初的主题仅仅是评判原告专家处理缺失数据的方式。在检查中，他们的方法在我看来不是最好的，甚至说是愚蠢的（例如，当不清楚“婚姻状况”时，叫他们“已婚”）。当我继续审查这些一手资料时，我很震惊数千亿美元在这种基础的数据分析中都浪费了。从更广泛的角度来看，大多数分析的逻辑似乎也完全混淆了。例如，所谓的不当行为似乎在几乎所有的计算中都没有出现，而且如“引起”或“归属于”的短语也经常互换，相互混淆。近一兆美元的损失在对错误的逻辑和糟糕的统计分析的基础上，因为我们“知道”的被告人的申辩是邪恶的有罪的，就应该归罪于被告方吗？如果问题是烟草行业对其产品的虚假广告为其带来万亿美元的利润，我会震惊但是沉默。但是，只是因为我们“知道”被告有罪，我们就可以接受这些报告使用错误的统计参数来设置数字吗？这意味着什么样的先例？这种伦理咨询在Rubin作了较为详细的讨论（2002）。 

Fabri: We have talked quite a lot about statistics. Let’s talk about some of your other passions in life, for example, music, audio systems and sports cars.

Fabri：关于统计我们已经谈论了很多。让我们聊聊你人生中的其他爱好，例如音乐，音频系统和跑车。


Don: There are other passions, too, and their order is very age dependent (I leave more to your perceptions). When a kid, for example, sports cars, both driving them and rebuilding them, was the top of those three hobbies. But age (poorer vision, slower reﬂexes, more aches and pains, etc.) shifted the balance more to music, both live and recorded—luckily my ears are still good enough to enjoy these, but as more age catches up, things may shift.

Don：我当然有很多乐趣，而且他们的顺序就是按照年龄来排列的（我留下了让你自己想象的空间）。当我是个小孩子，比如，一辆跑车，驾驶它还有重建它，是这三个中最重要的爱好。但当年龄增长（更差的视力，更慢的反应，更多的伤痛等等）会将爱好的平衡更多的转换为音乐，尤其是现场直播或者刻录的。很幸运我的耳朵足够好，能够享受这些，但随着年龄继续增加，爱好可能还会再变化。

Fan and Fabri: Well, it has been nearly three hours since we started the conversation. Here is the ﬁnal question before letting you go for dinner: What is your short advice to young researchers in statistics?

Fan and Fabri：好的，我们已经聊了接近三个小时了。在您去吃晚饭前，我们有最后一个问题想问您，您对统计里年轻的研究员有什么简短的建议吗？

Don: Have fun! Don’t be grumpy. If lucky, you may live to have a wonderful 70th birthday celebration!

Don：享受统计!不要暴躁。如果幸运的话，你可以有一个精彩的七十岁生日！

##ACKNOWLEDGMENTS##
##致谢##

We thank Elizabeth Zell, Guido Imbens, Tom Belin, Rod Little, Dale Rinkel and Alan Zaslavsky for helpful suggestions. This work is partially funded by NSF-SES Grant 1155697.

我们特别感谢Elizabeth Zell, Guido Imbens, Tom Belin, Rod Little, Dale Rinkel以及 Alan Zaslavsky提出的宝贵意见。这项工作有美国国家科学基金会的部分资金补助。